workflows:
  android-apk:
    name: Android APK Build (Debug)
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
